### ISSUE TITLE
Error: file already exists

### ISSUE THREAD

**Issue by lwotcynna** [annazc-ann/dl-organizer#1]
Unable to move file if there already a file with the same name in the destination folder.

**Comment by annazc-ann** [comment]
Oh sh*t why is this happening to mee T_T

**Comment by annazc-ann** [comment]
> Unable to move file if there already a file with the same name in the destination folder.

It turns out that you can solve that error with `try` and `except` statement bruh...

**Comment by lwotcynna** [comment]
> Unable to move file if there already a file with the same name in the destination folder.

The simplest way is to handle that traceback error with `try` and `except` statement bruh. 
I have just read this article:
https://realpython.com/python-exceptions/

**Comment by lwotcynna** [comment]
>
> The simplest way is to handle that traceback error with `try` and `except` statement bruh.
> I have just read this article:
> https://realpython.com/python-exceptions/

yeah I did and it works, thanks bro

**Comment by lwotcynna** [comment]
I think it solved
