### ISSUE TITLE
Can this program running in the background? 

### ISSUE THREAD

**Issue by lwotcynna** [annazc-ann/dl-organizer#2]
I want this program running in the background so it will immediately move my downloaded files once it finished.

**Comment by lwotcynna** [comment]
Yes, definitely it can.. you can add `while True:` statement to loop the program,  but it will throw an error like this when you download something:

`raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path '/sdcard/Download/Others/.org.chromium.Chromium.mhHgyM' already exists`

Maybe it moves your download part file created by chrome when it shouldn't be moved because it will cause a corrupted file. 
I don't know yet how to figure this out. 
I still need more learning

Can someone help me, please?

**Comment by annazc-ann** [comment]
> Yes, definitely it can.. you can add `while True:` statement to loop the program, but it will throw an error like this when you download something:
> 
> `raise Error("Destination path '%s' already exists" % real_dst) shutil.Error: Destination path '/sdcard/Download/Others/.org.chromium.Chromium.mhHgyM' already exists`
> 
> Maybe it moves your download part file created by chrome when it shouldn't be moved because it will cause a corrupted file.
> I don't know yet how to figure this out.
> I still need more learning
> 
> Can someone help me, please?

Hey, you can use `startswith() ` function bruh, ex. 
Maybe you can add this:
`if file == file.startswith('.org'):
   pass`

**Comment by lwotcynna** [comment]
> Yes, definitely it can.. you can add `while True:` statement to loop the program, but it will throw an error like this when you download something:
> 
> `raise Error("Destination path '%s' already exists" % real_dst) shutil.Error: Destination path '/sdcard/Download/Others/.org.chromium.Chromium.mhHgyM' already exists`
> 
> Maybe it moves your download part file created by chrome when it shouldn't be moved because it will cause a corrupted file.
> I don't know yet how to figure this out.
> I still need more learning
> 
> Can someone help me, please?

You are a mor*n!

**Comment by lwotcynna** [comment]
> `raise Error("Destination path '%s' already exists" % real_dst) shutil.Error: Destination path '/sdcard/Download/Others/.org.chromium.Chromium.mhHgyM' already exists`

Eventually I knew how to figure it out after struggling with stackoverflow and some python documentations... 

Firstly, you must exclude the hidden file (the file that its name is begin with dot `"."` ) 
to do this you can create a variable with `startswith()` function to check whether the file name is begin with dot or not, like this:

`hidden = file.startswith(".")`

after that add it to the except execution, it would be like this:

`>>> hidden = file.startswith(".")`
`>>> if hidden:`
`>>> • • • pass`

the `pass` execution will do nothing and exclude the hidden file in your case.

**Comment by lwotcynna** [comment]
>
> Eventually I knew how to figure it out after struggling with stackoverflow and some python documentations...
> 
> Firstly, you must exclude the hidden file (the file that its name is begin with dot `"."` )
> to do this you can create a variable with `startswith()` function to check whether the file name is begin with dot or not, like this:
> 
> `hidden = file.startswith(".")`
> 
> after that add it to the except execution, it would be like this:
> 
> `>>> hidden = file.startswith(".")`
> `>>> if hidden:`
> `>>> • • • pass`
> 
> the `pass` execution will do nothing and exclude the hidden file in your case.

Thanks bruh, it greatly works.. youma best friend 🤜

**Comment by lwotcynna** [comment]
> Thanks bruh, it greatly works.. youma best friend 🤜

My pleasure 😊. 
But aren't we the same person? I'm you

**Comment by lwotcynna** [comment]
> But aren't we the same person? I'm you

But you have a D.I.D?

**Comment by lwotcynna** [comment]
> But you have a D.I.D?

Haha, she wasnt appeared these days tho, I'm wondering why 🤔

**Comment by lwotcynna** [comment]
Haha your a liar!!

**Comment by lwotcynna** [comment]
It's not a D.I.D
You're just a damn chuunibyou!
